export const FIGHTCLUBMEETING = [
  {
    transcript: [
      'The',
      'first',
      'rule',
      'of',
      'Fight',
      'Club',
      'is:',
      'you',
      'do',
      'not',
      'talk',
      'about',
      'Fight',
      'Club.',
    ],
    translation:
      'Quy tắc đầu tiên của Fight Club là: bạn không được nói về Fight Club.',
  },
  {
    transcript: [
      'The',
      'second',
      'rule',
      'of',
      'Fight',
      'Club',
      'is:',
      'you',
      'do',
      'not',
      'talk',
      'about',
      'Fight',
      'Club.',
    ],
    translation:
      'Quy tắc thứ hai của Fight Club là: bạn không được nói về Fight Club.',
  },
  {
    transcript: [
      'If',
      'someone',
      'says',
      'stop,',
      'goes',
      'limp,',
      'or',
      'taps',
      'out,',
      'the',
      'fight',
      'is',
      'over.',
    ],
    translation:
      'Nếu ai đó nói "dừng", bất động hoặc ra hiệu xin thua, trận đấu kết thúc.',
  },
  {
    transcript: ['Only', 'two', 'guys', 'to', 'a', 'fight.'],
    translation: 'Chỉ có hai người tham gia một trận đấu.',
  },
  {
    transcript: ['One', 'fight', 'at', 'a', 'time.'],
    translation: 'Chỉ một trận đấu diễn ra tại một thời điểm.',
  },
  {
    transcript: ['No', 'shirts,', 'no', 'shoes.'],
    translation: 'Không áo, không giày.',
  },
  {
    transcript: [
      'Fights',
      'will',
      'go',
      'on',
      'as',
      'long',
      'as',
      'they',
      'have',
      'to.',
    ],
    translation: 'Các trận đấu sẽ tiếp tục cho đến khi chúng thực sự kết thúc.',
  },
  {
    transcript: [
      'If',
      'this',
      'is',
      'your',
      'first',
      'night',
      'at',
      'Fight',
      'Club,',
      'you',
      'have',
      'to',
      'fight.',
    ],
    translation:
      'Nếu đây là đêm đầu tiên của bạn ở Fight Club, bạn phải chiến đấu.',
  },
]
